### PR TITLE
make condor mode in postproc.py fully xrd dependent

### PR DESCRIPTION
**Pull request by mdunser**
in addition, it will had -ff the files, so the output on eos will already be compressed.

### CODE REVIEW

**Comment by cippy** [comment]
The reason files are copied back to afs is because condor copies output back to the submit directory from the worker node where they were created (this includes other input files that the job had to transfer in order to execute correctly)

In order to prevent the copy of the output back to the submit folder (i.e. /afs/...) it is enough to add the following line in the condor submit file
transfer_output_files = ""

Also, should we change this line
eos cp compressed/*.root $OUTDIR/
with the following
xrdcp compressed/*.root root://eoscms//$OUTDIR/ 
(or adding the prefix directly in $OUTDIR when creating the condor command)
to avoid using the eos mount?

**Comment by kdlong** [comment]
But aren't the jobs actually running from afs? So even turning off the transfer they'll show up in your afs directory. You either need to transfer the inputs (or use full paths to everything) + work from a directory local to the machine or just remove the files as done here.

**Comment by mdunser** [comment]
no, the jobs now run locally on the node. the only input needed to copy to the node are the keep and drop files, so those are copied by the exec script

**Comment by kdlong** [comment]
Ah, ok. Then Marco's suggestion is right, you can just turn off the transferring of output files.

**Review by cippy — APPROVED** [review]
All fine, can be merged

**Pull request merged**
